### ISSUE TITLE
Errors Installing Joom Gallery

### ISSUE THREAD

**Issue by dhebard** [JoomGallery/JoomGallery#118]
I have migrated a customers site from Joomla 1.5 to Joomal 3.7.  The customer was using the Pancea template and JoomGallery.  I have migrated the customer's data into the new Joomla 3.7 database and am trying to install the latest version of JoomGallery.  

I am receiving this error...

![joomgallery_error](https://user-images.githubusercontent.com/32205269/30758569-f1262742-9fa0-11e7-80c2-e042c3c5fe66.PNG)

Thank you,
Daniel

**Comment by Erftralle** [comment]
Hi,
please use this [migration script](https://github.com/JoomGallery/MigrateMVC2JUX) and proceed like described in [this documentation article](http://www.en.joomgallery.net/documentation/common-information/migration-from-jg-157-to-jg-2.html).
The description should also apply to a migration of the JommGallery 1.5.7.5 to the JoomGallery 3.3.3, assuming you use the aforementioned migration script.

**Comment by dhebard** [comment]
Thank you for this.  I have downloaded the migration script, however the documentation article says to install JoomGallery before running the migration script.  I am still unable to install JoomGallery. I receive the errors indicated in my earlier post concerning, not being able to drop a column from a table or add a column because it already exist.

 

Do you think it would be best for me to drop the JoomGallery data from my database and try a clean install?

 

Thank you

**Comment by Erftralle** [comment]
> Do you think it would be best for me to drop the JoomGallery data from my database and try a clean install?

It's not only the best but the only way to do it.

**Comment by dhebard** [comment]
Good day,

 

I apologize for being slow to respond, I have been out of the country for a short time.

 

I removed JoomGallery and then did a fresh install.  The component then installed correctly.  I tried using the migration script, but ran into issues because the tables in the old version of the DB are different that the tables in the new version and the script kept failing.  I manually added the needed columns to the new DB and was able to migrate all the data.  

 

The issue I have now is that even though the categories exist in the DB, they will not display in the backend for JoomGallery.  I tried to create a new category and when I tried to select the parent_id, nothing showed in the field and I am unable to type anything in the field either.

 

Please advise…

 

Thank you,

 

Daniel

**Comment by Erftralle** [comment]
Hi,

> I tried using the migration script, but ran into issues because the tables in the old version of the DB are different that the tables in the new version and the script kept failing. I manually added the needed columns to the new DB and was able to migrate all the data.

Yes, there have been a lot of database changes between the versions 1.5.7.5 and 3.3.3. The migration script should do the work for you and there is no need to adapt the database(s) before running the migration script. 

What exactly were the **_issues_**? Did the migration show an error message? Did you do a maintanance check of your old JoomGallery before and has everything been ok? 
Note, it is important, that you migrate **from version 1.5.7.5**, which has been the last JoomGallery version for Joomla 1.5.26 because the migration script assumes the database to be of that version.

> The issue I have now is that even though the categories exist in the DB, they will not display in the backend for JoomGallery. I tried to create a new category and when I tried to select the parent_id, nothing showed in the field and I am unable to type anything in the field either.

Obviously there went something wrong during the migration. 

Did the migration script report a succesfull migration? Did you check the migration log file? Are there any errors listed?

**Comment by dhebard** [comment]
I did migrate from v1.5.7.5.  How do I access the migration log file?  Can you provide the path?

 

I do not specifically remember the error messages, I would have to reset and try the migration again in order to duplicate.  Is that my best option at this point?

 

Thank you,

Daniel

**Comment by dhebard** [comment]
Current Maintenance view of Categories...

![image](https://user-images.githubusercontent.com/32205269/31689815-aac0d370-b35e-11e7-828e-fa6bedf23523.png)

**Comment by dhebard** [comment]
View in Category Manager

![image](https://user-images.githubusercontent.com/32205269/31689843-c4fddc6a-b35e-11e7-88af-40768a13fa7b.png)

**Comment by dhebard** [comment]
View of DB showing categories exists...

![image](https://user-images.githubusercontent.com/32205269/31690203-05b5b326-b360-11e7-921c-57b5e2424e10.png)

**Comment by dhebard** [comment]
However my joomgallery_category_details table is empty as it did not exist in version 1.5.7.5. Could that be the issue?
Thank you.

**Comment by Erftralle** [comment]
Hi,

> I did migrate from v1.5.7.5. How do I access the migration log file? Can you provide the path?

You will find it in your standard Joomla log path,  most prabably **/log/migration.mvc2jux.php**.

> Current Maintenance view of Categories...

The image shows the results of the maintenance of your JoomGallery 3.3.3. What I meant was that you should have done a maintenance check of your old JoomGallery 1.5.7.5 installation.

> View in Category Manager
> View of DB showing categories exists...

The root category entry is missing in your DB, this is an essential entry always existing in a clean fresh install of JoomGallery 3.3.3.

See also **/administrator/components/com_joomgallery/sql/install.mysql.utf8.sql**:
`INSERT INTO `#__joomgallery_catg` VALUES ('1', '0', 'ROOT', 'root', '0', '0', '0', '0', NULL, '1', '1', '0', '0', '', '0', NULL, '0', '', '', '', '', 0, 0);´ Note, it is not sufficient enough do insert this entry now manually. 

I'm wondering why because you said you removed JoomGallery and then did a fresh install. Obviously you removed not everything and/or the fresh install was not correct and clean.

Additionally the `asset_id`, `rgt` and `lft` (references to the Joomla asset table) are all wrong. The must not be 0.

As a result of all this the category manager view shows nothing.

> However my joomgallery_category_details table is empty as it did not exist in version 1.5.7.5. Could that be the issue?

No, it's ok that they are empty.

**Comment by dhebard** [comment]
I completely uninstalled JoomGallery and started over again.  This time the migration was successful with 12 errors.  Where is the log file located?  I would like to review the errors.

 

All my data, pics, and categories migrated successfully this time.

 

Thank you for your help!  Very much appreciated!

 

Daniel

**Comment by Erftralle** [comment]
Great that it worked.

> Where is the log file located?

I have already answered this question (see my previous comment).
