### ISSUE TITLE
V 3.2.2 Upload not working with AfterBurner2 template

### ISSUE THREAD

**Issue by HBREK** [JoomGallery/JoomGallery#54]
As requested by Erftralle (dev) the upload functionality fails in V.3.2.2, making a code modification necessary. Details here (in German): http://www.forum.joomgallery.net/index.php/topic,6297.0.html

**Comment by Chraneco** [comment]
Hi,

according to this there is a setting in the template for the system messages:
http://www.rockettheme.com/docs/joomla/templates/afterburner2/demo_override.md
Maybe it is disabled for you.

But it's strange because the system message container is a required element in Joomla templates already since a few major versions.
I'm wondering where are messages displayed for you? For example the success message after saving an article or the error messages when typing in a wrong password.

**Comment by HBREK** [comment]
Hi there,

"System Messages" are enabled in the theme, but no messages are displayed for this particular problem.

<img width="1133" alt="screen shot 2015-08-30 at 07 54 15" src="https://cloud.githubusercontent.com/assets/14028274/9565911/788abd90-4eec-11e5-9fce-6d64cc831f0a.png">

**Comment by Chraneco** [comment]
If this setting is enabled and the messages container does not show up in the frontend, this is problem with the template.

I am considering adding this piece of code into JoomGallery because it can't really harm, but please ask the template developer how the messages container works in this template because other parts of JoomGallery rely on this as well and other extensions do, too.

**Comment by HBREK** [comment]
Just sent RocketThemes a query about their message container. Will keep you posted.

**Comment by HBREK** [comment]
OK, here's the reply:

It is Gantry 4 that powers the generation of the System Messages. The System Messages are loaded via the template with:

<jdoc:include type="message" />
That code, in Gantry 4, is located within the Feature (http://docs.gantry.org/gantry4/configure/features): /libraries/gantry/features/systemmessages.php

Therefore, when the System Messages feature is configured in the template manager to a position, the <jdoc:include type="message" /> code is then injected. If the system messages work for other extensions, such as login, then it should work for JoomGallery. I hope that is helpful.

Cheers,

James Spencer
RocketTheme Support
support@rockettheme.com

Hope this helps!

**Comment by Chraneco** [comment]
Okay, thanks!
I looked at the code of the Gantry 4 framework and it makes sense now, but I'm even more convinced that this is a problem of the framework and not of JoomGallery. Here's the reason:

Gantry checks whether there are any messages currently in the message queue. If yes, it outputs the system message container. If there are no message, it doesn't output it. The upload of images (as well as many other things in JoomGallery) is asynchronous. There aren't any messages when the page loads. These messages are added when you hit the upload button or after the corresponding request completes.

For managing these messages JoomGallery uses Core Joomla methods of this file:
https://github.com/joomla/joomla-cms/blob/staging/media/system/js/core-uncompressed.js
Joomla.renderMessages() and Joomla.removeMessages() which expect the system messages container to be present at all times.
I'm pretty sure that other 3rd party components do the same.

Please send this information to them.

**Comment by Chraneco** [comment]
Closing because there were no further replies.
